

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:file:~Users/carol/h2db/matera
    username: h2sa
    password: admin
    driver-class-name: org.h2.Driver




server:
  port: 8072
