spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb
    username: h2
    password:
    driver-class-name: org.h2.Driver


server:
  port: 8072
